version: "3.3"
services:
  ner:
    image: parlamint_ner
    ports:
      - "5001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
