version: "3.3"
services:
  freeling:
    build: freeling
    image: parlamint_freeling
    environment:
      - FREELING_LANGUAGE=gl
    ports:
      - "5001"
  eagles2ud2:
    image: parlamint_eagles2ud2
    ports:
      - "5001"
  udpipes:
    image: parlamint_udpipes
    ports:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '4'
  ner:
    image: parlamint_ner
    ports:
      - "5001"
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - freeling
      - eagles2ud2
      - udpipes
      - ner
    ports:
      - "${FREELING_PORT}:5000"
      - "${EAGLES2UD2_PORT}:5001"
      - "${UDPIPES_PORT}:5002"
      - "${NER_PORT}:5003"
