require "rake/testtask"
require 'bundler/gem_tasks'
require_relative 'lib/parlamint/tasks'

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

task :default => :test
